### ISSUE TITLE
Word by word translation in Urdu

### ISSUE THREAD

**Issue by irfan-yusanif** [salamquran/SalamQuran-mysql-words#2]
Thanks for this awesome database collection, how can I get a word-by-word translation?
`quran_words` table has a translation column but it's only available in English and the translation database ([https://raw.githubusercontent.com/salamquran/SalamQuran-mysql-translations/master/salamquran_ur_kanzuliman.sql](https://raw.githubusercontent.com/salamquran/SalamQuran-mysql-translations/master/salamquran_ur_kanzuliman.sql)) contains the translation for the whole ayat. 

Is there a way I can get word-by-word translation in Urdu?

Thanks,
Irfan

**Comment by JohnAdib** [comment]
Hi
Currently we have word-by-word translation only for English.
